// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_800_file, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'MOCK_API_KEY_WEB',
    appId: '1:103015925046:web:103015925046',
    messagingSenderId: '103015925046',
    projectId: 'health-gaurd-ai',
    authDomain: 'health-gaurd-ai.firebaseapp.com',
    storageBucket: 'health-gaurd-ai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'MOCK_API_KEY_ANDROID',
    appId: '1:103015925046:android:103015925046',
    messagingSenderId: '103015925046',
    projectId: 'health-gaurd-ai',
    storageBucket: 'health-gaurd-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'MOCK_API_KEY_IOS',
    appId: '1:103015925046:ios:103015925046',
    messagingSenderId: '103015925046',
    projectId: 'health-gaurd-ai',
    storageBucket: 'health-gaurd-ai.appspot.com',
    iosBundleId: 'com.example.healthguard',
  );
}
