// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_800_file, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4nvV2Z0CDydQLzwYi8gLjyIQAfKAk5A8',
    appId: '1:125323774503:web:befeaebf7fddd90182dc02',
    messagingSenderId: '125323774503',
    projectId: 'health-ai-c2308',
    authDomain: 'health-ai-c2308.firebaseapp.com',
    storageBucket: 'health-ai-c2308.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIyxO4QJ2Ns6tEv-gs0kTO_VyzEmHX0k',
    appId: '1:125323774503:android:8412a948969f0dbb82dc02',
    messagingSenderId: '125323774503',
    projectId: 'health-ai-c2308',
    storageBucket: 'health-ai-c2308.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvDTzU0cVlgFJ8y2PKS7Bdbl75i0YXWI',
    appId: '1:125323774503:ios:a71ef5d3c630131782dc02',
    messagingSenderId: '125323774503',
    projectId: 'health-ai-c2308',
    storageBucket: 'health-ai-c2308.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1healthgaurdai',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvDTzU0cVlgFJ8y2PKS7Bdbl75i0YXWI',
    appId: '1:125323774503:ios:a71ef5d3c630131782dc02',
    messagingSenderId: '125323774503',
    projectId: 'health-ai-c2308',
    storageBucket: 'health-ai-c2308.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1healthgaurdai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4nvV2Z0CDydQLzwYi8gLjyIQAfKAk5A8',
    appId: '1:125323774503:web:0d4c7ff0d29eab9482dc02',
    messagingSenderId: '125323774503',
    projectId: 'health-ai-c2308',
    authDomain: 'health-ai-c2308.firebaseapp.com',
    storageBucket: 'health-ai-c2308.firebasestorage.app',
  );
}
